### ISSUE TITLE
How can I use the last modified of current items to check whether to run subsequent fetches?

### ISSUE THREAD

**Issue by eborisowIQVIA** [lucidworks/connectors-sdk-resources#26]
Hi,

My source content has metadata with the last modified date/time assigned to each item.  How can I use the last modified of the current content items to compare to the newly fetched content?  Do I need to execute a query on each item to retrieve it's last modified from Fusion on each iteration?  Or, is there something else in the API that will perform the check for me?  I'm wondering how this would work.

Regards,
Eric

**Comment by mwmitchell** [comment]
Hi @eborisowIQVIA - are you 

Individual Candidate items can store arbitrary metadata. This can be done through the withMetadata() method. Those items are then sent back to a fetcher as FetchInput items, and they should carry along the metadata that was present on the associated Candidates. You can see an example of that here: https://github.com/lucidworks/connectors-sdk-resources/blob/ce1fcbd3682de0de73f18203b5ba437fd5cd3d8c/java-sdk/connectors/random-connector/src/main/java/com/lucidworks/fusion/connector/plugin/RandomContentFetcher.java#L47

For a date/time or some other value representing an event, like "page 1 results done", or "change-set xyz done" (not a specific item's "last-modified") -- Checkpoints can be used, which are essentially progress markers, and like Candidates, can hold arbitrary metadata. Here are the basic rules for how they’re used:

* When using checkpoints, all Candidates should be emitted with isTransient=true
* Emit Checkpoints at the end of a batch, for example, if you're paginating over a sql result set, emit a Checkpoint at the end of each one, along with the "offset" - this will be sent as input in the next job run.
* Checkpoints will be the initial items received in subsequent job runs.
* All Checkpoints must be emitted on each job - meaning, previously emitted Checkpoints are not "remembered" and sent again to be fetched. For example, if a Checkpoint makes its way to a Fetcher, but the source system does not have changes since that Checkpoint's value, the Checkpoint must still be re-emitted, otherwise the next job-run will not receive the Checkpoint at all.
* Re-emitted Checkpoint metadata can be updated, or left as-is.

Hope this helps!

- Matt

**Comment by eborisowIQVIA** [comment]
For incremental crawls, I decided to emit one checkpoint at the end of the connector with the date/time stamp of the current job.

long currentTime = Instant.now().toEpochMilli();
		Map<String, Object> checkPointMap = Maps.newHashMap();
		checkPointMap.put("lastJobRunDateTime", currentTime);
		checkPointMap.put("isTransient", true);
		com.lucidworks.fusion.connector.plugin.api.fetcher.type.content.Checkpoint.Emitter checkPointTest = fetchContext.newCheckpoint(fetchContext.getRequestInfo().getId());
		checkPointTest.withMetadata(checkPointMap);
		checkPointTest.emit();

At the start of the next Fetch, I read the checkpoint and set the last run job time in a local variable.  One thing I learned is that I needed to explicitly delete the Checkpoint because it was emitted again on subsequent jobs.  (Sounds like a bug, according to your description of not supposed to be getting submitted again).

Date lastJobRunDateTime = null;
		DateFormat m_ISO8601NoSec = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
	    if (input.getMetadata().containsKey("isTransient"))
	    {
	    	Map<String, Object> metaData = input.getMetadata();
	    	if (metaData != null)
	    	{
	    		logger.info("Checkpoint {} lastJobRunDateTime {}", input.getId(), metaData.get("lastJobRunDateTime"));
	    		
	    		if (this.myConfig.isIncremental())
	    		{
		    		if (metaData.get("lastJobRunDateTime") != null)
		    		{
		    			long lastRunDateTimeLong = (Long) metaData.get("lastJobRunDateTime");
		    			lastJobRunDateTime = new Date(lastRunDateTimeLong);
		    			logger.info("Last run date time (formatted) {}", m_ISO8601NoSec.format(lastJobRunDateTime));
		    		}
	    		}
	    		
	    		Delete.Emitter checkPointDelete = fetchContext.newDelete(input.getId());
	    		checkPointDelete.emit();
	    	}
	    }

One final note.  If you try to implement this on a cluster of connectors-rpc where you have a preFetch that retrieves the full list of items in a 'light' way and then you depend on fetch to get the details, you will end up with a complete mess if you tried to emit CheckPoints for each of your previous items (to avoid indexing the same items over and over).  They will be 'sprayed' all over your connectors-rpc cluster and you end up with random CheckPoints on each node.  I'm not sure what was the point of this.  You should have the ability to receive the CheckPoints in the preFetch stage.  That way, you could emit the last items and do something during preFetch with the previous items.

**Comment by mwmitchell** [comment]
Excellent feedback @eborisowIQVIA, thanks for taking the time to write that up. We'll read and discuss what you've shared.
